name: CI-SFTP
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SFTP Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_SERVER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.REMOTE_PATH }}
            git pull
            composer install --no-dev --optimize-autoloader
            php bin/console d:m:m -n
            npm install
            npm run build
